export const types = {
    GET_USER: "GET_USER",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_USER: "LOGOUT_USER",
    LOGIN_FAIL: "LOGIN_FAIL",
    AUTH_ERROR: "AUTH_ERROR",
    REMOVE_ERRORS: "REMOVE_ERRORS",

    GET_TRACKS: "GET_TRACKS",
    GET_TRACK: "GET_TRACK",
    GET_ALBUMS: "GET_ALBUMS",
    GET_ALBUM: "GET_ALBUM",
    GET_ARTISTS: "GET_ARTISTS",
    GET_ARTIST: "GET_ARTIST",


    PLAY_TRACK: "PLAY_TRACK",
    PAUSE_TRACK: "PAUSE_TRACK"
}